### ISSUE TITLE
keycloak not starting with command from the documentation

### ISSUE THREAD

**Issue by bigon** [keycloak/keycloak-web#271]
### Describe the bug

At multiple places (ie for [docker](https://www.keycloak.org/getting-started/getting-started-docker)) the documentation tells the user to use the `start-dev` option, but with that option, keycloak immediately stops.

This seems to come from this commit https://github.com/keycloak/keycloak-web/commit/7a6f19d7bab04deb6d43ceda22036396f00191b2

More over, even when removing `start-dev` the user cannot login as the "admin" user doesn't seem to be created

### Version

HEAD

### Expected behavior

Documentation just works

### Actual behavior

keycloak is not starting and the user is not even created

### How to Reproduce?

`docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:16.1.1 start-dev`

**Comment by lemmywrap** [comment]
In order to get it working for now, this what I did:
`docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:16.1.1`

When the container is up and running, execute the following:
`docker exec <container_name> sh /opt/jboss/keycloak/bin/add-user-keycloak.sh -r master -u admin -p admin`

Should give the following output:
`Added 'admin' to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json', restart server to load user`

Restart the container.

Hope this helps.
